### ISSUE TITLE
sync with remote fails with invalid date error

### ISSUE THREAD

**Issue by adicirstei** [creationix/tedit#61]
I have just installed the chrome app v0.2.22, cloned a repo, made a chage, commited then when I tried to sync with remote I go t an error regarding the dates. See the screenshot:
![image](https://cloud.githubusercontent.com/assets/1694688/8100807/0ab386ba-1019-11e5-9c4b-bfd1c4bfa3e3.png)

**Comment by creationix** [comment]
Interesting, sounds like Github changed something on their end again.  I'll see if I can fix it.

**Comment by creationix** [comment]
I can't reproduce it.  I even tried with a fork of your bootstrap repo and it commits and syncs fine for me using tedit chrome app. https://github.com/adicirstei/bootstrap/compare/master...creationix:master

**Comment by creationix** [comment]
I tested on Linux.  It shouldn't matter, but are what OS are you using?

**Comment by adicirstei** [comment]
Windows 7 64 bits. Both chrome app and online app behaved the same. I'll try capture the request.

**Comment by adicirstei** [comment]
the function `encodeCommit` (which I wasn't able to findout in which module resides) calls `encodePerson` which, in turn calls `encodeDate` which I think is the culprit:

```
function encodeDate(date) {
  var seconds = date.seconds - (date.offset) * 60;
  var d = new Date(seconds * 1000);
  var string = d.toISOString();
  var hours = (date.offset / 60)|0;
  var minutes = date.offset % 60;
  string = string.substring(0, string.lastIndexOf(".")) +
    (date.offset > 0 ? "-" : "+") +
    twoDigit(hours) + ":" + twoDigit(minutes);
  return string;
}
```

the issue being that `twoDigit(-3)` returns `"0-3"`.

Hope this helps.
Adrian

**Comment by creationix** [comment]
Ahh, it's your timezone being different.  My local timezone is US Central.

**Comment by creationix** [comment]
This should help https://github.com/creationix/js-github/commit/b645bcd798b5011ee563399362e28d231f6a4d19

I'll see if I can publish an update to the website and chrome app.  I've not done any in a long while, hopefully I can remember how.

**Comment by adicirstei** [comment]
:) don't hurry! In the change you made I think you meant:
```javascript
if (date.offset <= 0) date.offset = -date.offset;
```
instead of:
```javascript
if (offset <= 0) offset = -offset;
```

**Comment by adicirstei** [comment]
The good news is that after fixing the fix the push is working.

**Comment by creationix** [comment]
Thanks for the code review.  I got busy with work stuff, I'll try this later.
